token = '' #Webex Teams Token - https://developer.webex.com/my-apps/new/bot
subscription_key = '' #Azure Subscription-Key - Can use Face API Free
maps_key = '' #GoogleMaps-Key - https://cloud.google.com/maps-platform/
apikey= '' #Meraki-API-Key - https://developer.cisco.com/meraki/api/#!authorization/obtaining-your-meraki-api-key
room_id = '' #Webex Teams roomId - https://developer.webex.com/docs/api/v1/rooms/get-room-details
mentioned_id = '' #Webex Teams mentionedPeople (email id of members that needs to be added inside the room)
network_id = '' #Meraki Network ID - To obtain and note the Network ID execute the following steps: starting from - Go to https://developer.cisco.com/meraki/api-v1/#!get-organizations > click Configuration
mssn = '' #Meraki MS S/N - switch serial number
camlist = [] #Meraki MV S/N List - camera serial number
